# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 953acb19e55ff179e2f59f029e823937de4ed276d612798f08bbfb4316c20b7850ffe5839b5c8ae27b59f64521ecd9e7fc2d0c2f84e12613d30b448765a31f68

test:
  secret_key_base: 2c3445a29f5a1fd37f231c57ef2034476c1db7699dee3988b8b770f85824bf23198d44626540ec0be7961edd70932e045bb979202fb0434480c44995c09259d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
